services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php
  php:
    container_name: yii_php
    build: ./images/Php74
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii
    depends_on:
      - postgres_sql
  postgres_sql:
    container_name: yii_postgres_sql
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=yii
      - POSTGRES_PASSWORD=yii
      - POSTGRES_ROOT_PASSWORD=yii
      - POSTGRES_DATABASE=yii
    networks:
      - yii

networks:
  yii:

volumes:
  db: